# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ba8fc57b5fd4966ed196a6c5d9bbe7966dd3737a42a1aef43ff4bde16f62ad00376fb397c2487249804c1603e9e26e95b1284691dee301e04153127217a7df0

test:
  secret_key_base: 4547f7229f792ef27cf907fb85f38526cca7e928970b2bd8dbc0106b8c7171aa84ae0202b5e0c9dd4e8f84469e7b4bbcde31d455d9f354851f5e6dcfb050cc18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
